name:                segfault

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - file-embed
    - bytestring

executables:
  segfault-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - segfault
